/**
 * Error codes for payment operations
 */
export enum PaymentErrorCode {
  // General payment errors
  PAYMENT_ERROR = 'PAYMENT_ERROR',
  PAYMENT_INVALID_RESPONSE_ERROR = 'PAYMENT_INVALID_RESPONSE_ERROR',

  // Configuration errors
  PAYMENT_CONFIGURATION_ERROR = 'PAYMENT_CONFIGURATION_ERROR',

  // Operation errors
  PAYMENT_INITIALIZATION_ERROR = 'PAYMENT_INITIALIZATION_ERROR',
  PAYMENT_VERIFICATION_ERROR = 'PAYMENT_VERIFICATION_ERROR',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_REFUND_ERROR = 'PAYMENT_REFUND_ERROR',
  PAYMENT_CANCELLATION_ERROR = 'PAYMENT_CANCELLATION_ERROR',

  // Gateway errors
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_GATEWAY_ERROR',
  PAYMENT_GATEWAY_TIMEOUT = 'PAYMENT_GATEWAY_TIMEOUT',

  // Validation errors
  INVALID_PAYMENT_AMOUNT = 'INVALID_PAYMENT_AMOUNT',
  UNSUPPORTED_CURRENCY = 'UNSUPPORTED_CURRENCY',
  UNSUPPORTED_PAYMENT_CHANNEL = 'UNSUPPORTED_PAYMENT_CHANNEL',
  PAYMENT_VALIDATION_ERROR = 'PAYMENT_VALIDATION_ERROR',

  // Business logic errors
  DUPLICATE_PAYMENT = 'DUPLICATE_PAYMENT',
  INVALID_REFUND_AMOUNT = 'INVALID_REFUND_AMOUNT',
  PAYMENT_NOT_REFUNDABLE = 'PAYMENT_NOT_REFUNDABLE',
}
