packages:
  # Core PorkAte packages (non-extractable)
  - 'packages/*'
  
  # Standalone packages (extraction-ready - can move to separate repos)
  - 'packages/standalone/*'
  
  # Examples
  - 'examples/*'
