/**
 * NoSQL error codes
 */
export enum NoSQLErrorCode {
  // Configuration errors
  NOSQL_CONFIGURATION_ERROR = 'NOSQL_CONFIGURATION_ERROR',

  // Connection errors
  NOSQL_CONNECTION_ERROR = 'NOSQL_CONNECTION_ERROR',
  NOSQL_CONNECTION_TIMEOUT = 'NOSQL_CONNECTION_TIMEOUT',
  NOSQL_DISCONNECTION_ERROR = 'NOSQL_DISCONNECTION_ERROR',

  // Operation errors
  NOSQL_INSERT_ERROR = 'NOSQL_INSERT_ERROR',
  NOSQL_QUERY_ERROR = 'NOSQL_QUERY_ERROR',
  NOSQL_UPDATE_ERROR = 'NOSQL_UPDATE_ERROR',
  NOSQL_DELETE_ERROR = 'NOSQL_DELETE_ERROR',
  NOSQL_BULK_INSERT_ERROR = 'NOSQL_BULK_INSERT_ERROR',

  // Data errors
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
  INVALID_TRANSACTION_DATA = 'INVALID_TRANSACTION_DATA',

  // Health check errors
  NOSQL_HEALTH_CHECK_FAILED = 'NOSQL_HEALTH_CHECK_FAILED',

  // Generic error
  NOSQL_ERROR = 'NOSQL_ERROR',
}
